version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
      - image: circleci/mysql:8.0
    environment:
      - DB_CONNECTION: circle_testing
    working_directory: ~/current
    steps:
      - checkout
      - run:
          name: Echo Test
          command: echo "Test"
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - ""
      - run:
          name: Exec deploy command
          command: |
            ssh -o "StrictHostKeyChecking=no" ${SSH_USER}@${SSH_HOST} "~/deploy.sh"
# コメントアウト
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master